### ISSUE TITLE
How i can integrate my bot?

### ISSUE THREAD

**Issue by neoll4ik** [julianYaman/discord-bot-dashboard#32]
Hello, i writting my bot in Discord bot maker, can i integrate my bot? and how its work? Thx.  

first start error:

npm start

> discord-bot-dashboard@0.0.1 start /home/neoll/bot/discord-bot-dashboard
> nodemon discord-bot-sourcefiles/main.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node discord-bot-sourcefiles/main.js`
module.js:540
    throw err;
    ^

Error: Cannot find module '../private_config.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/neoll/bot/discord-bot-dashboard/discord-bot-sourcefiles/main.js:10:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by julianYaman** [comment]
There is a file missing: ../private_config.json

You must create this file which contains every needed value for this project. 
The example for this is the file called ../config.json
