### ISSUE TITLE
module.js:674

### ISSUE THREAD

**Issue by neoll4ik** [julianYaman/discord-bot-dashboard#34]
module.js:674
    throw err;
    ^

SyntaxError: /home/neoll/BOTS/discord-bot-dashboard/private_config.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/neoll/BOTS/discord-bot-dashboard/discord-bot-sourcefiles/main.js:10:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
[nodemon] app crashed - waiting for file changes before starting...

add bot token in config.json, and change /discord-bot-sourcefiles/main.js    to client.login(config.token);

**Comment by RatingGull27** [comment]
@neoll4ik look like you put the private_config.json into the files and with it

**Comment by julianYaman** [comment]
just refering here to #32
